import Link from 'next/link'
import { ArrowRight, Crosshair } from 'lucide-react'
import { SiteShell } from '@/components/site-shell'
import { ContactStrip, FinalCTA, CallButton, WhatsAppButton } from '@/components/site-actions'
import { areas } from '@/lib/site-data'

export function AreasPage() {
  return <SiteShell><main><section className="page-hero page-hero-simple"><div className="hero-overlay" /><div className="container page-hero-content"><p className="eyebrow"><span className="live-dot" /> Local recovery coverage</p><h1>Vehicle Recovery Across Kent</h1><p className="hero-copy">Local recovery around Rochester, Maidstone and Medway, with nationwide vehicle transportation available when your vehicle needs to move further.</p><div className="hero-actions"><CallButton /><WhatsAppButton /></div></div></section><ContactStrip /><section className="section"><div className="container content-grid"><div><p className="eyebrow blue">Where we work</p><h2>Local when you need<br /><em>recovery.</em></h2><p className="lead-copy">LM Recovery covers the listed local areas across Kent for vehicle recovery. Tell us where the vehicle is and what you need moved so we can discuss the job directly.</p></div><div className="area-list">{areas.map((area) => <div key={area}><span>{area}</span><ArrowRight /></div>)}</div></div></section><section className="section pale-section"><div className="container content-grid"><div><p className="eyebrow blue">Two types of coverage</p><h2>Recovery locally.<br /><em>Transport nationwide.</em></h2></div><div className="coverage-cards"><article><span className="coverage-number">01</span><h3>Local recovery coverage</h3><p>Rochester, Maidstone, Chatham, Strood, Gillingham, Medway and Kent.</p><Link href="/breakdown-recovery">Breakdown recovery <ArrowRight /></Link></article><article><span className="coverage-number">02</span><h3>Nationwide vehicle transport</h3><p>Planned vehicle transportation for longer-distance routes across England.</p><Link href="/vehicle-transport">Vehicle transport <ArrowRight /></Link></article></div></div></section><section className="section"><div className="container areas-map-large"><div className="map-card"><div className="map-lines" /><span className="map-pin pin-one" /><span className="map-pin pin-two" /><span className="map-pin pin-three" /><div className="map-label"><Crosshair /><span><strong>Kent based</strong><small>Local recovery coverage</small></span></div></div><div><p className="eyebrow blue">Need to check an area?</p><h2>Tell us where the vehicle <em>is.</em></h2><p className="lead-copy">If your location is outside the local area, get in touch anyway. Nationwide vehicle transport is a separate service and can be discussed around your route.</p><div className="hero-actions"><CallButton /><WhatsAppButton /></div></div></div></section><FinalCTA /></main></SiteShell>
}
