import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Check, Crosshair, ShieldCheck, Truck } from 'lucide-react'
import { Gallery } from '@/components/gallery'
import { FAQ } from '@/components/faq'
import { SiteShell } from '@/components/site-shell'
import { CallButton, ContactStrip, FinalCTA, TrustRating, WhatsAppButton } from '@/components/site-actions'
import { RecoveryRequestForm } from '@/components/recovery-request-form'
import { areas, faqs, genuineImages, serviceLinks } from '@/lib/site-data'

export default function LMRecoveryHome() {
  return <SiteShell><main id="top">
    <section className="hero" aria-labelledby="hero-title"><div className="hero-image"><Image src={genuineImages[6]} alt="LM Recovery truck transporting a vehicle" fill priority sizes="100vw" /></div><div className="hero-overlay" /><div className="container hero-content"><p className="eyebrow"><span className="live-dot" /> 24/7 Vehicle Recovery • Kent</p><h1 id="hero-title">Stranded?<br /><em>We&apos;ll get you moving.</em></h1><p className="hero-copy">24/7 vehicle recovery and transport across Maidstone, Medway, Kent and nationwide.</p><div className="trust-row"><TrustRating /><div><ShieldCheck /><small>Direct contact</small></div><div><Truck /><small>Recovery &amp; transport</small></div></div><div className="hero-actions"><CallButton>Call now — 07500 473262</CallButton><WhatsAppButton>WhatsApp us</WhatsAppButton></div><p className="direct-line">Speak directly with LM Recovery.</p></div><div className="hero-tag"><Truck /> Recovery &amp; transportation</div></section>
    <ContactStrip />
    <section className="quote-section section"><div className="container quote-grid"><div className="section-intro"><p className="eyebrow blue">Recovery request</p><h2>Need recovery<br /><em>now?</em></h2><p>Send the vehicle and route details through WhatsApp so LM Recovery can discuss your recovery or transport.</p><div className="callout"><Crosshair /><span>Prefer to speak now?<br /><a href="tel:07500473262">Call 07500 473262</a></span></div></div><RecoveryRequestForm /></div></section>
    <section className="services-section section"><div className="container"><div className="section-heading"><div><p className="eyebrow blue">What we do</p><h2>Recovery &amp; transport<br /><em>services</em></h2></div><p>Practical help for breakdowns, collections and vehicle movement across Kent and beyond.</p></div><div className="service-grid">{serviceLinks.map((service, index) => <article className="service-card" key={service.href}><div className="service-image"><Image src={service.image} alt={`${service.title} by LM Recovery`} fill sizes="(max-width: 700px) 100vw, 33vw" /><span>0{index + 1}</span></div><div className="service-card-content"><h3>{service.title}</h3><p>{service.text}</p><Link href={service.href}>Learn more <ArrowRight /></Link></div></article>)}</div></div></section>
    <section className="proof-section section"><div className="container proof-grid"><div><p className="eyebrow yellow">A local reputation</p><h2>Trusted by drivers<br /><em>across Kent.</em></h2><TrustRating /><p>Real local reputation built through recovery and transport work.</p><span className="text-link text-link-disabled">Google rating: 4.9 from 112 reviews</span></div><div className="review-summary"><span className="review-summary-mark">G</span><div><strong>Google reviews</strong><p>4.9 / 5 from 112 reviews</p><span className="review-stars">★★★★★</span></div></div></div></section>
    <section className="why-section section"><div className="container why-grid"><div className="why-image"><Image src={genuineImages[3]} alt="LM Recovery truck loading a van" fill sizes="(max-width: 700px) 100vw, 50vw" /></div><div className="why-content"><p className="eyebrow blue">Why LM Recovery</p><h2>A local recovery company you can <em>actually reach.</em></h2><p>LM Recovery is a direct, family-run recovery and transportation company operated by Liam.</p><div className="why-list">{[['24/7 availability', 'Help when you need it.'], ['Deal directly with LM Recovery', 'No call centre between you and the recovery operator.'], ['Local Kent service', 'Recovery around Rochester, Maidstone, Medway and Kent.'], ['Nationwide transport', 'Longer-distance vehicle movement can be discussed.']].map(([title, text]) => <div key={title}><Check /><span><strong>{title}</strong><small>{text}</small></span></div>)}</div></div></div></section>
    <section className="areas-section section"><div className="container areas-grid"><div><p className="eyebrow blue">Local &amp; nationwide</p><h2>Vehicle recovery<br />across Kent <em>&amp; beyond.</em></h2><p>Local recovery coverage includes the listed Kent areas. Nationwide vehicle transportation is available as a separate planned service.</p><div className="area-chips">{areas.map((area) => <Link href="/areas-we-cover" key={area}>{area}</Link>)}</div></div><div className="map-card"><div className="map-lines" /><span className="map-pin pin-one" /><span className="map-pin pin-two" /><span className="map-pin pin-three" /><div className="map-label"><Crosshair /><span><strong>Kent based</strong><small>Nationwide vehicle transport</small></span></div></div></div></section>
    <Gallery />
    <section className="section process-section"><div className="container"><div className="section-heading"><div><p className="eyebrow blue">Simple from start to finish</p><h2>Need a vehicle <em>moved?</em></h2></div><p>Tell LM Recovery what you need and get a direct answer about the recovery or transport details.</p></div><div className="process-grid"><div className="process-step"><span>01</span><div><h3>Call or WhatsApp</h3><p>Tell us your vehicle and location.</p></div></div><div className="process-step"><span>02</span><div><h3>Share the details</h3><p>Confirm pickup, destination and vehicle condition.</p></div></div><div className="process-step"><span>03</span><div><h3>Arrange the move</h3><p>LM Recovery discusses the practical next step.</p></div></div></div></div></section>
    <section className="section faq-section"><div className="container faq-grid"><div><p className="eyebrow blue">Good to know</p><h2>Frequently asked<br /><em>questions.</em></h2><p>Can&apos;t find what you need? Call LM Recovery and speak directly with the operator.</p><CallButton /></div><FAQ items={faqs.general} /></div></section>
    <FinalCTA emergency />
  </main></SiteShell>
}
