import Link from 'next/link'
import Image from 'next/image'
import { ArrowRight, Check, ClipboardList, Crosshair, MessageCircle, Truck } from 'lucide-react'
import { Gallery } from '@/components/gallery'
import { FAQ } from '@/components/faq'
import { HeroMedia } from '@/components/hero-media'
import { SiteShell } from '@/components/site-shell'
import { CallButton, ContactStrip, FinalCTA, WhatsAppButton } from '@/components/site-actions'
import { RecoveryRequestForm } from '@/components/recovery-request-form'
import { CoverageMap } from '@/components/coverage-map'
import { areas, faqs, genuineImages, serviceLinks } from '@/lib/site-data'

export default function LMRecoveryHome() {
  return <SiteShell><main id="top" className="brand-preview-page">
    <section className="hero" aria-labelledby="hero-title"><HeroMedia image="/lm-recovery-hero-2.jpg" alt="LM Recovery truck transporting a vehicle" /><div className="hero-overlay" /><div className="container hero-content"><p className="eyebrow"><span className="live-dot" /> 24/7 Vehicle Recovery • Kent</p><h1 id="hero-title">Vehicle Recovery <em>&amp; Transport</em> Across Kent</h1><p className="hero-copy">24/7 recovery for drivers across Rochester, Maidstone, Medway and surrounding Kent areas, with nationwide vehicle transport available.</p><div className="hero-actions"><CallButton>Call now — 07500 473262</CallButton><WhatsAppButton>WhatsApp</WhatsAppButton></div><div className="hero-trust-line"><span className="hero-trust-stars">★★★★★</span><strong>4.9</strong><span>Google rating</span><span>112 reviews</span><span>24/7 service</span><span>Direct contact</span></div></div></section>
    <ContactStrip />
    <section className="quote-section section"><div className="container quote-grid"><div className="section-intro"><h2>Need recovery <em>now?</em></h2><p>Send your vehicle and route details to LM Recovery, or call directly if you need immediate assistance.</p><div className="info-panel request-callout"><Crosshair /><span><strong>Prefer to speak now?</strong><a href="tel:07500473262">07500 473262</a></span></div></div><RecoveryRequestForm /></div></section>
    <section className="services-section section"><div className="container"><div className="section-heading"><div><p className="eyebrow blue">What we do</p><h2>Recovery &amp; transport <em>services</em></h2></div><p>Practical help for breakdowns, collections and vehicle movement across Kent and beyond.</p></div><div className="service-grid">{serviceLinks.map((service) => <article className="service-card" key={service.href}><div className="service-image"><Image src={service.image} alt={`${service.title} by LM Recovery`} fill sizes="(max-width: 700px) 100vw, (max-width: 1024px) 50vw, 33vw" /></div><div className="service-card-content"><h3>{service.title}</h3><p>{service.text}</p><Link href={service.href}>Learn more <ArrowRight /></Link></div></article>)}</div></div></section>
    <section className="proof-section section"><div className="container proof-grid"><div><p className="eyebrow yellow">Local reputation</p><h2>Trusted by drivers <em>across Kent.</em></h2></div><div className="trust-proof"><strong>4.9</strong><span aria-hidden="true">★</span><p>112 Google Reviews</p></div></div></section>
    <section className="why-section section"><div className="container why-grid"><div className="why-image"><Image src={genuineImages[0]} alt="LM Recovery vehicle recovery work" fill sizes="(max-width: 700px) 100vw, 50vw" /></div><div className="why-content"><p className="eyebrow blue">Why LM Recovery</p><h2>Direct recovery and transport <em>when you need it.</em></h2><div className="why-list"><div><Check /><span><strong>Direct contact</strong><small>Speak directly with LM Recovery rather than navigating a call centre.</small></span></div><div><Check /><span><strong>Local Kent recovery</strong><small>Recovery across Rochester, Maidstone, Medway and surrounding Kent areas.</small></span></div><div><Check /><span><strong>Vehicle transport</strong><small>Planned vehicle movement across Kent and nationwide.</small></span></div></div></div></div></section>
    <section className="areas-section section"><div className="container areas-grid"><div><h2>Recovery across <em>Kent.</em></h2><p>LM Recovery provides local vehicle recovery across Rochester, Maidstone, Medway and surrounding Kent areas.</p><ul className="homepage-area-list">{areas.map((area) => <li key={area}><Link href="/areas-we-cover">{area}<ArrowRight aria-hidden="true" /></Link></li>)}</ul><div className="nationwide-note"><strong>Nationwide transport</strong><span>Planned vehicle transportation is also available across the UK.</span></div></div><CoverageMap /></div></section>
    <Gallery />
    <section className="section process-section"><div className="container"><div className="section-heading"><div><h2>How recovery <em>works.</em></h2></div><p>Call or message LM Recovery with the vehicle and location details.</p></div><div className="process-grid"><div className="process-step"><span className="process-step-icon"><MessageCircle /></span><span className="process-step-number">01</span><div><h3>Call or WhatsApp</h3><p>Tell LM Recovery where the vehicle is and what has happened.</p></div></div><div className="process-step"><span className="process-step-icon"><ClipboardList /></span><span className="process-step-number">02</span><div><h3>Share the details</h3><p>Confirm the vehicle, pickup and destination information.</p></div></div><div className="process-step"><span className="process-step-icon"><Truck /></span><span className="process-step-number">03</span><div><h3>Arrange the move</h3><p>LM Recovery discusses the recovery or transport details directly with you.</p></div></div></div></div></section>
    <section className="section faq-section"><div className="container faq-grid"><div><p className="eyebrow blue">Good to know</p><h2>Frequently asked<br /><em>questions.</em></h2><p>Can&apos;t find what you need? Call LM Recovery and speak directly with the operator.</p><CallButton /></div><FAQ items={faqs.general} /></div></section>
    <FinalCTA emergency />
  </main></SiteShell>
}
